∵ GraphDL: A concrete implementation of GraphDL can function as a Database with Resources as instances of Nouns

■ Noun:
  _resources:     [Resource]

□ Resource:
  _type:          Noun
  _description:   A Resource is a specific instance of a Noun
  instance:       Noun.resources
  data:           json
  subjectOf:      [Action.subject]
  objectOf:       [Action.object]
  requests:       [Request.resource]
  created:        Request.create
  createdAt:      created->timestamp
  createdBy:      created->user
  updated:        Request.update
  updatedAt:      updated->timestamp
  updatedBy:      updated->user
  deleted:        Request.delete
  deletedAt:      deleted->timestamp
  deletedBy:      deleted->user
  tenant:         created->tenant