# fly.toml app configuration file generated for graphdl-payload on 2023-10-31T04:31:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "graphdl-payload"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
